//! The document vocabulary is independent of the application's current interface language.
//! Only framing is translated; organization names and authored text remain unchanged.
use super::INVALID_FORMAT;

pub(super) struct Language {
    pub code: &'static str,
    pub name: &'static str,
    pub organization: &'static str,
    pub description: &'static str,
    pub background: &'static str,
    pub direct: &'static str,
    pub department: &'static str,
    pub member: &'static str,
    pub rank: &'static str,
    pub role: &'static str,
    pub receives: &'static str,
    pub task: &'static str,
    pub delivers: &'static str,
    pub role_member: &'static str,
    pub role_organization_admin: &'static str,
    pub role_department_admin: &'static str,
}

pub(super) const LANGUAGES: &[Language] = &[
    Language {
        code: "zh-CN",
        name: "中文",
        organization: "# 组织：",
        description: "## 简介",
        background: "## 公共背景",
        direct: "## 直属成员",
        department: "## 部门：",
        member: "### 成员：",
        rank: "- 职级：",
        role: "- 管理身份：",
        receives: "#### 接收内容",
        task: "#### 职责",
        delivers: "#### 交付要求",
        role_member: "普通成员",
        role_organization_admin: "组织管理员",
        role_department_admin: "部门管理员",
    },
    Language {
        code: "zh-TW",
        name: "繁體中文",
        organization: "# 組織：",
        description: "## 簡介",
        background: "## 公共背景",
        direct: "## 直屬成員",
        department: "## 部門：",
        member: "### 成員：",
        rank: "- 職級：",
        role: "- 管理身分：",
        receives: "#### 接收內容",
        task: "#### 職責",
        delivers: "#### 交付要求",
        role_member: "一般成員",
        role_organization_admin: "組織管理員",
        role_department_admin: "部門管理員",
    },
    Language {
        code: "en-US",
        name: "English",
        organization: "# Organization: ",
        description: "## Description",
        background: "## Shared Background",
        direct: "## Direct Members",
        department: "## Department: ",
        member: "### Member: ",
        rank: "- Rank: ",
        role: "- Management role: ",
        receives: "#### Receives",
        task: "#### Responsibilities",
        delivers: "#### Deliverables",
        role_member: "Member",
        role_organization_admin: "Organization administrator",
        role_department_admin: "Department administrator",
    },
    Language {
        code: "en-GB",
        name: "English (United Kingdom)",
        organization: "# Organisation: ",
        description: "## Description",
        background: "## Shared Background",
        direct: "## Direct Members",
        department: "## Department: ",
        member: "### Member: ",
        rank: "- Rank: ",
        role: "- Management role: ",
        receives: "#### Receives",
        task: "#### Responsibilities",
        delivers: "#### Deliverables",
        role_member: "Member",
        role_organization_admin: "Organisation administrator",
        role_department_admin: "Department administrator",
    },
    Language {
        code: "ko-KR",
        name: "한국어",
        organization: "# 조직: ",
        description: "## 소개",
        background: "## 공통 배경",
        direct: "## 직속 구성원",
        department: "## 부서: ",
        member: "### 구성원: ",
        rank: "- 직급: ",
        role: "- 관리 역할: ",
        receives: "#### 받는 내용",
        task: "#### 담당 업무",
        delivers: "#### 산출물",
        role_member: "일반 구성원",
        role_organization_admin: "조직 관리자",
        role_department_admin: "부서 관리자",
    },
    Language {
        code: "ja-JP",
        name: "日本語",
        organization: "# 組織：",
        description: "## 概要",
        background: "## 共通の背景",
        direct: "## 直属メンバー",
        department: "## 部門：",
        member: "### メンバー：",
        rank: "- 職位：",
        role: "- 管理上の役割：",
        receives: "#### 受け取る内容",
        task: "#### 担当業務",
        delivers: "#### 成果物",
        role_member: "一般メンバー",
        role_organization_admin: "組織管理者",
        role_department_admin: "部門管理者",
    },
    Language {
        code: "fr-FR",
        name: "Français",
        organization: "# Organisation : ",
        description: "## Description",
        background: "## Contexte commun",
        direct: "## Membres directs",
        department: "## Département : ",
        member: "### Membre : ",
        rank: "- Niveau : ",
        role: "- Rôle de gestion : ",
        receives: "#### Entrées",
        task: "#### Responsabilités",
        delivers: "#### Livrables",
        role_member: "Membre",
        role_organization_admin: "Administrateur de l’organisation",
        role_department_admin: "Administrateur du département",
    },
    Language {
        code: "it-IT",
        name: "Italiano",
        organization: "# Organizzazione: ",
        description: "## Descrizione",
        background: "## Contesto condiviso",
        direct: "## Membri diretti",
        department: "## Reparto: ",
        member: "### Membro: ",
        rank: "- Livello: ",
        role: "- Ruolo gestionale: ",
        receives: "#### Input",
        task: "#### Responsabilità",
        delivers: "#### Risultati attesi",
        role_member: "Membro",
        role_organization_admin: "Amministratore dell’organizzazione",
        role_department_admin: "Amministratore del reparto",
    },
    Language {
        code: "ru-RU",
        name: "Русский",
        organization: "# Организация: ",
        description: "## Описание",
        background: "## Общий контекст",
        direct: "## Прямые участники",
        department: "## Отдел: ",
        member: "### Участник: ",
        rank: "- Уровень: ",
        role: "- Роль управления: ",
        receives: "#### Входные данные",
        task: "#### Обязанности",
        delivers: "#### Ожидаемые результаты",
        role_member: "Участник",
        role_organization_admin: "Администратор организации",
        role_department_admin: "Администратор отдела",
    },
];

pub(super) fn for_code(code: &str) -> Result<&'static Language, String> {
    LANGUAGES
        .iter()
        .find(|language| language.code == code)
        .ok_or_else(|| INVALID_FORMAT.into())
}

pub(super) fn from_declaration(line: &str) -> Result<&'static Language, String> {
    let name = line
        .strip_suffix('\r')
        .unwrap_or(line)
        .strip_prefix("Language:")
        .or_else(|| line.strip_prefix("Language："))
        .ok_or(INVALID_FORMAT)?
        .trim();
    LANGUAGES
        .iter()
        .find(|language| language.name == name)
        .ok_or_else(|| INVALID_FORMAT.into())
}
