packages:
  - packages/*

allowBuilds:
  core-js-pure: false
  electron: true
  electron-winstaller: true
  esbuild: true
  node-pty: true

patchedDependencies:
  pptxgenjs@4.0.1: patches/pptxgenjs@4.0.1.patch
