import type { LanguageInput } from 'shiki/core'
import type { GitReviewSyntaxLanguageId } from '../syntax/fileLanguageRegistry'

export type GitReviewHighlightableLanguageId = Exclude<GitReviewSyntaxLanguageId, 'text'>

/**
 * The complete, deliberately bounded grammar set supported by Git review.
 *
 * Keep every import path literal: Vite can then emit only this product-owned language set instead
 * of walking Shiki's full language and alias bundles. `satisfies` makes additions to the file
 * language registry fail type-checking until their grammar-loading cost is accepted here too.
 */
export const GIT_REVIEW_SYNTAX_LANGUAGE_LOADERS = {
  'angular-html': () => import('@shikijs/langs/angular-html'),
  'angular-ts': () => import('@shikijs/langs/angular-ts'),
  astro: () => import('@shikijs/langs/astro'),
  bat: () => import('@shikijs/langs/bat'),
  bibtex: () => import('@shikijs/langs/bibtex'),
  blade: () => import('@shikijs/langs/blade'),
  c: () => import('@shikijs/langs/c'),
  clojure: () => import('@shikijs/langs/clojure'),
  cmake: () => import('@shikijs/langs/cmake'),
  codeowners: () => import('@shikijs/langs/codeowners'),
  cpp: () => import('@shikijs/langs/cpp'),
  csharp: () => import('@shikijs/langs/csharp'),
  css: () => import('@shikijs/langs/css'),
  csv: () => import('@shikijs/langs/csv'),
  dart: () => import('@shikijs/langs/dart'),
  docker: () => import('@shikijs/langs/docker'),
  dotenv: () => import('@shikijs/langs/dotenv'),
  elixir: () => import('@shikijs/langs/elixir'),
  elm: () => import('@shikijs/langs/elm'),
  erb: () => import('@shikijs/langs/erb'),
  erlang: () => import('@shikijs/langs/erlang'),
  fish: () => import('@shikijs/langs/fish'),
  fsharp: () => import('@shikijs/langs/fsharp'),
  'git-commit': () => import('@shikijs/langs/git-commit'),
  'git-rebase': () => import('@shikijs/langs/git-rebase'),
  go: () => import('@shikijs/langs/go'),
  graphql: () => import('@shikijs/langs/graphql'),
  groovy: () => import('@shikijs/langs/groovy'),
  handlebars: () => import('@shikijs/langs/handlebars'),
  haskell: () => import('@shikijs/langs/haskell'),
  hcl: () => import('@shikijs/langs/hcl'),
  html: () => import('@shikijs/langs/html'),
  ini: () => import('@shikijs/langs/ini'),
  java: () => import('@shikijs/langs/java'),
  javascript: () => import('@shikijs/langs/javascript'),
  jinja: () => import('@shikijs/langs/jinja'),
  json: () => import('@shikijs/langs/json'),
  json5: () => import('@shikijs/langs/json5'),
  jsonc: () => import('@shikijs/langs/jsonc'),
  jsonl: () => import('@shikijs/langs/jsonl'),
  jsx: () => import('@shikijs/langs/jsx'),
  julia: () => import('@shikijs/langs/julia'),
  just: () => import('@shikijs/langs/just'),
  kotlin: () => import('@shikijs/langs/kotlin'),
  latex: () => import('@shikijs/langs/latex'),
  less: () => import('@shikijs/langs/less'),
  log: () => import('@shikijs/langs/log'),
  lua: () => import('@shikijs/langs/lua'),
  make: () => import('@shikijs/langs/make'),
  markdown: () => import('@shikijs/langs/markdown'),
  mdx: () => import('@shikijs/langs/mdx'),
  mermaid: () => import('@shikijs/langs/mermaid'),
  nginx: () => import('@shikijs/langs/nginx'),
  nim: () => import('@shikijs/langs/nim'),
  nix: () => import('@shikijs/langs/nix'),
  'objective-c': () => import('@shikijs/langs/objective-c'),
  'objective-cpp': () => import('@shikijs/langs/objective-cpp'),
  ocaml: () => import('@shikijs/langs/ocaml'),
  perl: () => import('@shikijs/langs/perl'),
  php: () => import('@shikijs/langs/php'),
  powershell: () => import('@shikijs/langs/powershell'),
  prisma: () => import('@shikijs/langs/prisma'),
  proto: () => import('@shikijs/langs/proto'),
  python: () => import('@shikijs/langs/python'),
  r: () => import('@shikijs/langs/r'),
  rst: () => import('@shikijs/langs/rst'),
  ruby: () => import('@shikijs/langs/ruby'),
  rust: () => import('@shikijs/langs/rust'),
  sass: () => import('@shikijs/langs/sass'),
  scala: () => import('@shikijs/langs/scala'),
  scss: () => import('@shikijs/langs/scss'),
  shellscript: () => import('@shikijs/langs/shellscript'),
  solidity: () => import('@shikijs/langs/solidity'),
  sql: () => import('@shikijs/langs/sql'),
  svelte: () => import('@shikijs/langs/svelte'),
  swift: () => import('@shikijs/langs/swift'),
  'system-verilog': () => import('@shikijs/langs/system-verilog'),
  terraform: () => import('@shikijs/langs/terraform'),
  toml: () => import('@shikijs/langs/toml'),
  tsx: () => import('@shikijs/langs/tsx'),
  tsv: () => import('@shikijs/langs/tsv'),
  typescript: () => import('@shikijs/langs/typescript'),
  v: () => import('@shikijs/langs/v'),
  verilog: () => import('@shikijs/langs/verilog'),
  vue: () => import('@shikijs/langs/vue'),
  'vue-html': () => import('@shikijs/langs/vue-html'),
  wasm: () => import('@shikijs/langs/wasm'),
  wgsl: () => import('@shikijs/langs/wgsl'),
  xml: () => import('@shikijs/langs/xml'),
  yaml: () => import('@shikijs/langs/yaml'),
  zig: () => import('@shikijs/langs/zig')
} satisfies Record<GitReviewHighlightableLanguageId, LanguageInput>

export function getGitReviewSyntaxLanguageLoader(language: string): LanguageInput | undefined {
  if (!Object.hasOwn(GIT_REVIEW_SYNTAX_LANGUAGE_LOADERS, language)) return undefined
  return GIT_REVIEW_SYNTAX_LANGUAGE_LOADERS[language as GitReviewHighlightableLanguageId]
}
