import { defaultThemeIdsByColorScheme, lightTheme } from './frontendTheme'
import { DEFAULT_APP_LANGUAGE } from './languageRegistry'
import type { ColorSchemePreference, FrontendTheme } from './frontendTheme'
import type { AppLanguage } from './frontendTranslations'
import { getGitReviewCssVariables } from './themes/gitReviewTheme'

export const FRONTEND_CONFIG_STORAGE_KEY = 'mycopilot.frontend-config'

export const frontendConfig = {
  language: DEFAULT_APP_LANGUAGE satisfies AppLanguage,
  colorSchemePreference: 'system' satisfies ColorSchemePreference,
  themeIdsByColorScheme: defaultThemeIdsByColorScheme,
  typography: {
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "SF Pro Text", "SF Pro Display", "Segoe UI", Inter, ui-sans-serif, sans-serif',
    monoFontFamily: 'ui-monospace, "SFMono-Regular", SFMono-Regular, Menlo, Consolas, monospace',
    codeSize: '12px',
    sidebar: {
      actionSize: '14px',
      sectionTitleSize: '14px',
      bodySize: '14px'
    },
    rightPanel: {
      titleSize: '14px'
    },
    settings: {
      titleSize: '24px',
      navSize: '14px',
      bodySize: '14px',
      sectionHeadingSize: '16px',
      sectionTitleSize: '16px'
    },
    configuration: {
      titleSize: '24px',
      labelSize: '14px'
    },
    chat: {
      inputSize: '14px',
      toolbarSize: '14px',
      messageSize: '15px',
      assistantSize: '15px',
      activitySize: '14px',
      activityDetailSize: '14px',
      metadataSize: '12px',
      approvalSize: '13px'
    },
    scale: {
      xs: '12px',
      sm: '14px',
      md: '14px',
      base: '14px',
      lg: '15px',
      xl: '16px',
      '2xl': '18px',
      '3xl': '20px',
      dialogTitle: '24px'
    },
    weight: {
      regular: '400',
      control: '400',
      medium: '420',
      contentMedium: '430',
      semibold: '450',
      bold: '500',
      sectionStrong: '500',
      strong: '500',
      select: '500',
      heavy: '520',
      black: '520',
      extraBlack: '520',
      display: '520'
    },
    lineHeight: {
      none: '1',
      tight: '1.1',
      compact: '1.2',
      normal: '1.3',
      relaxed: '1.45',
      body: '1.58',
      chat: '1.55',
      roomy: '1.7',
      sidebar: '20px',
      control: '24px',
      title: '32px',
      sidebarTitle: '26px',
      rightTitle: '22px',
      metadata: '1.25'
    }
  },
  colors: lightTheme.colors,
  radius: {
    none: '0',
    xxs: '3px',
    xs: '7px',
    sm: '8px',
    md: '9px',
    lg: '10px',
    xl: '11px',
    '2xl': '12px',
    control: '13px',
    row: '14px',
    card: '16px',
    popover: '18px',
    message: '21px',
    composer: '24px',
    dialog: '28px',
    pill: '999px'
  },
  shadow: lightTheme.shadow,
  effect: {
    blurSubtle: 'blur(3px)',
    blurSidebar: 'blur(14px)',
    blurPopover: 'blur(18px)',
    blurDialog: 'blur(22px)'
  },
  icon: {
    size: {
      sm: '16px',
      md: '17px',
      base: '18px',
      lg: '19px',
      xl: '20px',
      '2xl': '21px',
      '4xl': '23px'
    },
    stroke: {
      thin: '1.75',
      regular: '1.8',
      medium: '1.9',
      strong: '2',
      extraBlack: '2.8',
      ultra: '3'
    }
  },
  layout: {
    titlebarHeight: '52px',
    sidebarActionHeight: '29px',
    sidebarHeaderHeight: '29px',
    sidebarActionWidth: '28px',
    settingsNavWidth: 'clamp(286px, 23.8vw, 344px)'
  }
} as const

export type FrontendConfig = typeof frontendConfig

export function getFrontendCssVariables(
  config: FrontendConfig = frontendConfig,
  theme: FrontendTheme = lightTheme
): Record<string, string> {
  return {
    '--mc-font-family': config.typography.fontFamily,
    '--mc-mono-font-family': config.typography.monoFontFamily,
    '--mc-font-size-code': config.typography.codeSize,

    '--mc-font-size-sidebar-action': config.typography.sidebar.actionSize,
    '--mc-font-size-sidebar-section-title': config.typography.sidebar.sectionTitleSize,
    '--mc-font-size-sidebar-body': config.typography.sidebar.bodySize,
    '--mc-font-size-right-panel-title': config.typography.rightPanel.titleSize,
    '--mc-font-size-settings-title': config.typography.settings.titleSize,
    '--mc-font-size-settings-nav': config.typography.settings.navSize,
    '--mc-font-size-settings-body': config.typography.settings.bodySize,
    '--mc-font-size-settings-section-heading': config.typography.settings.sectionHeadingSize,
    '--mc-font-size-settings-section-title': config.typography.settings.sectionTitleSize,
    '--mc-font-size-configuration-title': config.typography.configuration.titleSize,
    '--mc-font-size-configuration-label': config.typography.configuration.labelSize,
    '--mc-font-size-chat-input': config.typography.chat.inputSize,
    '--mc-font-size-chat-toolbar': config.typography.chat.toolbarSize,
    '--mc-font-size-chat-message': config.typography.chat.messageSize,
    '--mc-font-size-chat-assistant': config.typography.chat.assistantSize,
    '--mc-font-size-chat-activity': config.typography.chat.activitySize,
    '--mc-font-size-chat-activity-detail': config.typography.chat.activityDetailSize,
    '--mc-font-size-chat-metadata': config.typography.chat.metadataSize,
    '--mc-font-size-chat-approval': config.typography.chat.approvalSize,
    '--mc-font-size-xs': config.typography.scale.xs,
    '--mc-font-size-sm': config.typography.scale.sm,
    '--mc-font-size-md': config.typography.scale.md,
    '--mc-font-size-base': config.typography.scale.base,
    '--mc-font-size-lg': config.typography.scale.lg,
    '--mc-font-size-xl': config.typography.scale.xl,
    '--mc-font-size-2xl': config.typography.scale['2xl'],
    '--mc-font-size-3xl': config.typography.scale['3xl'],
    '--mc-font-size-dialog-title': config.typography.scale.dialogTitle,
    '--mc-font-weight-regular': config.typography.weight.regular,
    '--mc-font-weight-control': config.typography.weight.control,
    '--mc-font-weight-medium': config.typography.weight.medium,
    '--mc-font-weight-content-medium': config.typography.weight.contentMedium,
    '--mc-font-weight-semibold': config.typography.weight.semibold,
    '--mc-font-weight-bold': config.typography.weight.bold,
    '--mc-font-weight-section-strong': config.typography.weight.sectionStrong,
    '--mc-font-weight-strong': config.typography.weight.strong,
    '--mc-font-weight-select': config.typography.weight.select,
    '--mc-font-weight-heavy': config.typography.weight.heavy,
    '--mc-font-weight-black': config.typography.weight.black,
    '--mc-font-weight-extra-black': config.typography.weight.extraBlack,
    '--mc-font-weight-display': config.typography.weight.display,
    '--mc-line-height-none': config.typography.lineHeight.none,
    '--mc-line-height-tight': config.typography.lineHeight.tight,
    '--mc-line-height-compact': config.typography.lineHeight.compact,
    '--mc-line-height-normal': config.typography.lineHeight.normal,
    '--mc-line-height-relaxed': config.typography.lineHeight.relaxed,
    '--mc-line-height-body': config.typography.lineHeight.body,
    '--mc-line-height-chat': config.typography.lineHeight.chat,
    '--mc-line-height-roomy': config.typography.lineHeight.roomy,
    '--mc-line-height-sidebar': config.typography.lineHeight.sidebar,
    '--mc-line-height-control': config.typography.lineHeight.control,
    '--mc-line-height-title': config.typography.lineHeight.title,
    '--mc-line-height-sidebar-title': config.typography.lineHeight.sidebarTitle,
    '--mc-line-height-right-title': config.typography.lineHeight.rightTitle,
    '--mc-line-height-metadata': config.typography.lineHeight.metadata,

    '--mc-color-text-primary': theme.colors.text.primary,
    '--mc-color-text-strong': theme.colors.text.strong,
    '--mc-color-text-secondary': theme.colors.text.secondary,
    '--mc-color-text-muted': theme.colors.text.muted,
    '--mc-color-text-subtle': theme.colors.text.subtle,
    '--mc-color-text-inverse': theme.colors.text.inverse,
    '--mc-color-text-danger': theme.colors.text.danger,
    '--mc-color-text-accent': theme.colors.text.accent,
    '--mc-color-icon-default': theme.colors.icon.default,
    '--mc-color-icon-muted': theme.colors.icon.muted,
    '--mc-color-icon-subtle': theme.colors.icon.subtle,
    '--mc-color-icon-accent': theme.colors.icon.accent,
    '--mc-color-icon-danger': theme.colors.icon.danger,
    '--mc-color-icon-success': theme.colors.icon.success,
    '--mc-color-avatar-background': theme.colors.avatar.background,
    '--mc-color-surface-left-panel': theme.colors.surface.leftPanel,
    '--mc-color-surface-main-panel': theme.colors.surface.mainPanel,
    '--mc-color-surface-right-panel': theme.colors.surface.rightPanel,
    '--mc-color-surface-card': theme.colors.surface.card,
    '--mc-color-surface-input': theme.colors.surface.input,
    '--mc-color-surface-popover': theme.colors.surface.popover,
    '--mc-color-surface-muted': theme.colors.surface.muted,
    '--mc-color-surface-selected': theme.colors.surface.selected,
    '--mc-color-surface-selected-subtle': theme.colors.surface.selectedSubtle,
    '--mc-color-surface-info-subtle': theme.colors.surface.infoSubtle,
    '--mc-color-surface-success-subtle': theme.colors.surface.successSubtle,
    '--mc-color-surface-neutral-subtle': theme.colors.surface.neutralSubtle,
    '--mc-color-surface-disabled': theme.colors.surface.disabled,
    '--mc-color-surface-danger-subtle': theme.colors.surface.dangerSubtle,
    '--mc-color-surface-danger-soft': theme.colors.surface.dangerSoft,
    '--mc-color-surface-error-subtle': theme.colors.surface.errorSubtle,
    '--mc-color-surface-glass': theme.colors.surface.glass,
    '--mc-color-surface-glass-strong': theme.colors.surface.glassStrong,
    '--mc-color-surface-glass-input': theme.colors.surface.glassInput,
    '--mc-color-border-hairline': theme.colors.border.hairline,
    '--mc-color-border-subtle': theme.colors.border.subtle,
    '--mc-color-border-default': theme.colors.border.default,
    '--mc-color-border-strong': theme.colors.border.strong,
    '--mc-color-border-error': theme.colors.border.error,
    '--mc-color-border-right-toolbar-divider': theme.colors.border.rightToolbarDivider,
    '--mc-color-button-primary-bg': theme.colors.button.primaryBg,
    '--mc-color-button-primary-bg-hover': theme.colors.button.primaryBgHover,
    '--mc-color-button-primary-text': theme.colors.button.primaryText,
    '--mc-color-button-secondary-bg': theme.colors.button.secondaryBg,
    '--mc-color-button-secondary-bg-hover': theme.colors.button.secondaryBgHover,
    '--mc-color-button-secondary-text': theme.colors.button.secondaryText,
    '--mc-color-button-danger-bg': theme.colors.button.dangerBg,
    '--mc-color-button-danger-bg-hover': theme.colors.button.dangerBgHover,
    '--mc-color-button-danger-text': theme.colors.button.dangerText,
    '--mc-color-button-danger-soft-text': theme.colors.button.dangerSoftText,
    '--mc-color-button-danger-soft-bg': theme.colors.button.dangerSoftBg,
    '--mc-color-button-danger-soft-bg-hover': theme.colors.button.dangerSoftBgHover,
    '--mc-color-control-selected-background': theme.colors.control.selectedBackground,
    '--mc-color-control-selected-text': theme.colors.control.selectedText,
    '--mc-color-sidebar-text-secondary': theme.colors.sidebar.textSecondary,
    '--mc-color-sidebar-text-active': theme.colors.sidebar.textActive,
    '--mc-color-sidebar-translucent-tint': theme.colors.sidebar.translucentTint,
    '--mc-color-settings-content-title': theme.colors.settings.contentTitle,
    '--mc-color-settings-content-text': theme.colors.settings.contentText,
    '--mc-color-settings-content-muted': theme.colors.settings.contentMuted,
    '--mc-color-state-hover': theme.colors.state.hover,
    '--mc-color-state-active': theme.colors.state.active,
    '--mc-color-focus-ring': theme.colors.state.focusRing,
    '--mc-color-resize-handle': theme.colors.state.resizeHandle,
    '--mc-color-overlay': theme.colors.state.overlay,
    '--mc-color-overlay-light': theme.colors.state.overlayLight,
    '--mc-color-status-success-text': theme.colors.status.successText,
    '--mc-color-status-success-surface': theme.colors.status.successSurface,
    '--mc-color-diff-addition-text': theme.colors.diff.additionText,
    '--mc-color-diff-deletion-text': theme.colors.diff.deletionText,
    ...getGitReviewCssVariables(theme.colors.gitReview),
    '--mc-color-data-viz-input': theme.colors.dataViz.input,
    '--mc-color-data-viz-output': theme.colors.dataViz.output,
    '--mc-color-data-viz-output-thinking': theme.colors.dataViz.outputThinking,
    '--mc-color-source-badge-text': theme.colors.sourceBadge.text,
    '--mc-color-source-badge-background': theme.colors.sourceBadge.background,
    '--mc-color-shimmer-highlight': theme.colors.effect.shimmerHighlight,
    '--mc-color-terminal-background': theme.colors.terminal.background,
    '--mc-color-terminal-foreground': theme.colors.terminal.foreground,
    '--mc-color-terminal-cursor': theme.colors.terminal.cursor,
    '--mc-color-terminal-selection-background': theme.colors.terminal.selectionBackground,
    '--mc-color-terminal-black': theme.colors.terminal.black,
    '--mc-color-terminal-red': theme.colors.terminal.red,
    '--mc-color-terminal-green': theme.colors.terminal.green,
    '--mc-color-terminal-yellow': theme.colors.terminal.yellow,
    '--mc-color-terminal-blue': theme.colors.terminal.blue,
    '--mc-color-terminal-magenta': theme.colors.terminal.magenta,
    '--mc-color-terminal-cyan': theme.colors.terminal.cyan,
    '--mc-color-terminal-white': theme.colors.terminal.white,
    '--mc-color-terminal-bright-black': theme.colors.terminal.brightBlack,
    '--mc-color-terminal-bright-red': theme.colors.terminal.brightRed,
    '--mc-color-terminal-bright-green': theme.colors.terminal.brightGreen,
    '--mc-color-terminal-bright-yellow': theme.colors.terminal.brightYellow,
    '--mc-color-terminal-bright-blue': theme.colors.terminal.brightBlue,
    '--mc-color-terminal-bright-magenta': theme.colors.terminal.brightMagenta,
    '--mc-color-terminal-bright-cyan': theme.colors.terminal.brightCyan,
    '--mc-color-terminal-bright-white': theme.colors.terminal.brightWhite,
    '--mc-color-media-viewer-foreground': theme.colors.mediaViewer.foreground,
    '--mc-color-media-viewer-backdrop': theme.colors.mediaViewer.backdrop,
    '--mc-color-media-viewer-control-background': theme.colors.mediaViewer.controlBackground,
    '--mc-color-media-viewer-control-hover': theme.colors.mediaViewer.controlHover,
    '--mc-color-media-viewer-focus-ring': theme.colors.mediaViewer.focusRing,
    '--mc-color-media-viewer-menu-background': theme.colors.mediaViewer.menuBackground,
    '--mc-color-media-viewer-menu-border': theme.colors.mediaViewer.menuBorder,
    '--mc-radius-none': config.radius.none,
    '--mc-radius-xxs': config.radius.xxs,
    '--mc-radius-xs': config.radius.xs,
    '--mc-radius-sm': config.radius.sm,
    '--mc-radius-md': config.radius.md,
    '--mc-radius-lg': config.radius.lg,
    '--mc-radius-xl': config.radius.xl,
    '--mc-radius-2xl': config.radius['2xl'],
    '--mc-radius-control': config.radius.control,
    '--mc-radius-row': config.radius.row,
    '--mc-radius-card': config.radius.card,
    '--mc-radius-popover': config.radius.popover,
    '--mc-radius-message': config.radius.message,
    '--mc-radius-composer': config.radius.composer,
    '--mc-radius-dialog': config.radius.dialog,
    '--mc-radius-pill': config.radius.pill,
    '--mc-shadow-none': theme.shadow.none,
    '--mc-shadow-hairline': theme.shadow.hairline,
    '--mc-shadow-focus': theme.shadow.focus,
    '--mc-shadow-composer': theme.shadow.composer,
    '--mc-shadow-popover': theme.shadow.popover,
    '--mc-shadow-popover-large': theme.shadow.popoverLarge,
    '--mc-shadow-sidebar-menu': theme.shadow.sidebarMenu,
    '--mc-shadow-card': theme.shadow.card,
    '--mc-shadow-dialog': theme.shadow.dialog,
    '--mc-shadow-media-viewer-menu': theme.shadow.mediaViewerMenu,
    '--mc-effect-blur-subtle': config.effect.blurSubtle,
    '--mc-effect-blur-sidebar': config.effect.blurSidebar,
    '--mc-effect-blur-popover': config.effect.blurPopover,
    '--mc-effect-blur-dialog': config.effect.blurDialog,
    '--mc-icon-size-sm': config.icon.size.sm,
    '--mc-icon-size-md': config.icon.size.md,
    '--mc-icon-size-base': config.icon.size.base,
    '--mc-icon-size-lg': config.icon.size.lg,
    '--mc-icon-size-xl': config.icon.size.xl,
    '--mc-icon-size-2xl': config.icon.size['2xl'],
    '--mc-icon-size-4xl': config.icon.size['4xl'],
    '--mc-icon-stroke-thin': config.icon.stroke.thin,
    '--mc-icon-stroke-regular': config.icon.stroke.regular,
    '--mc-icon-stroke-medium': config.icon.stroke.medium,
    '--mc-icon-stroke-strong': config.icon.stroke.strong,
    '--mc-icon-stroke-extra-black': config.icon.stroke.extraBlack,
    '--mc-icon-stroke-ultra': config.icon.stroke.ultra,
    '--mc-layout-titlebar-height': config.layout.titlebarHeight,
    '--mc-layout-sidebar-action-height': config.layout.sidebarActionHeight,
    '--mc-layout-sidebar-header-height': config.layout.sidebarHeaderHeight,
    '--mc-layout-sidebar-action-width': config.layout.sidebarActionWidth,
    '--mc-layout-settings-nav-width': config.layout.settingsNavWidth
  }
}
