export {
  AUTOMATION_SCHEMA_VERSION,
  AUTOMATION_PERMISSION_MODE_VERSION,
  AUTOMATION_ERROR_CODE,
  AUTOMATION_LIST_METHOD,
  AUTOMATION_GET_METHOD,
  AUTOMATION_CREATE_METHOD,
  AUTOMATION_UPDATE_METHOD,
  AUTOMATION_SET_ENABLED_METHOD,
  AUTOMATION_RUN_NOW_METHOD,
  AUTOMATION_DELETE_METHOD,
  AUTOMATION_RUNS_LIST_METHOD,
  AUTOMATION_ATTENTION_SUMMARY_METHOD,
  AUTOMATION_ATTENTION_ACKNOWLEDGE_METHOD,
  AUTOMATION_EVENT_NOTIFICATION_METHOD,
  AUTOMATION_RESYNC_NOTIFICATION_METHOD
} from './automations/constants'

export type {
  AutomationStatus,
  AutomationPermissionMode,
  AutomationNotificationPolicy,
  AutomationWeekday,
  AutomationIntervalUnit,
  AutomationCustomFrequency,
  AutomationScheduleInput,
  AutomationSchedule,
  AutomationReasoningProjection,
  AutomationDestinationInput,
  AutomationDestination,
  AutomationHealth,
  AutomationRunStatus,
  AutomationRunTriggerKind,
  AutomationReportKind,
  AutomationAttentionKind,
  AutomationAttention,
  AutomationRun,
  AutomationTargetSnapshot,
  AutomationTask,
  AutomationTaskSummary,
  AutomationMutableConfigInput,
  AutomationListInput,
  AutomationGetInput,
  AutomationCreateInput,
  AutomationUpdateInput,
  AutomationSetEnabledInput,
  AutomationRunNowInput,
  AutomationDeleteInput,
  AutomationRunsListInput,
  AutomationAttentionSummaryInput,
  AutomationAttentionAcknowledgeInput,
  AutomationListOutput,
  AutomationRunsListOutput,
  AutomationAttentionSummaryOutput,
  AutomationAttentionAcknowledgeOutput,
  AutomationDeleteOutput,
  AutomationOpenRequest,
  AutomationEventKind,
  AutomationEvent,
  AutomationResync,
  AutomationErrorKind,
  AutomationErrorData
} from './automations/types'

export { parseAutomationScheduleInput } from './automations/schedule'

export { parseAutomationTask } from './automations/task'

export { parseAutomationAttention, parseAutomationRun } from './automations/run'

export {
  parseAutomationListInput,
  parseAutomationGetInput,
  parseAutomationCreateInput,
  parseAutomationUpdateInput,
  parseAutomationSetEnabledInput,
  parseAutomationRunNowInput,
  parseAutomationDeleteInput,
  parseAutomationRunsListInput,
  parseAutomationAttentionSummaryInput,
  parseAutomationAttentionAcknowledgeInput,
  parseAutomationListOutput,
  parseAutomationRunsListOutput,
  parseAutomationAttentionSummaryOutput,
  parseAutomationAttentionAcknowledgeOutput,
  parseAutomationDeleteOutput,
  parseAutomationOpenRequest,
  parseAutomationEvent,
  parseAutomationResync,
  parseAutomationErrorData
} from './automations/rpc'
