const english = {
  issue_node_model_unavailable: 'This node’s model is unavailable. Select an available model.',
  issue_node_model: 'Select a model for this node.',
  noEnabledModels: 'No enabled models',
  modelNotSelected: 'No model selected',
  modelUnavailable: 'Model unavailable',
  selectModel: 'Select model',
  model: 'Model',
  paletteTitle: 'Add node',
  nodeSettings: 'Node settings',
  quickSettings: 'Selected agent',
  details: 'Configure',
  backgroundEmpty: 'No shared background yet.',
  editBackground: 'Edit shared background',
  nodeTaskTab: 'Task',
  searchNodes: 'Search nodes',
  addNode: 'Add node',
  closeInspector: 'Close inspector',
  unsaved: 'Unsaved',
  redo: 'Redo',
  undo: 'Undo',
  structureTab: 'Structure',
  basicInfo: 'Basic information',
  copy: 'Duplicate template',
  copySuffix: 'copy',
  saveCopy: 'Save as copy',
  stash: 'Save editing draft',
  stashed: 'Editing draft saved. The published template is unchanged.',
  restoredDraft: 'Editing draft restored. The published template is unchanged.',
  pendingEdits: 'Editing draft',
  usageTitle: 'Update a template in use?',
  usageDescription:
    'The following workflows use this template. Saving will require them to review and confirm their conversation bindings before use.',
  runningTitle: 'This template is currently running',
  runningDescription:
    'A running workflow uses this template, so the original cannot be overwritten. Save your changes as a separate copy, or keep an editing draft for later.',
  runningInstance: 'Running',
  confirmPublish: 'Save and require review',
  title: 'Workflow templates',
  create: 'New workflow template',
  edit: 'Edit workflow template',
  delete: 'Delete workflow template',
  empty: 'No workflow templates yet',
  name: 'Name',
  namePlaceholder: 'For example: Product proposal review, release acceptance',
  descriptionPlaceholder: 'Describe the tasks this workflow handles and when to use it',
  backgroundPlaceholder: 'Add the goals, context, and shared requirements every node should know',
  description: 'Short description',
  background: 'Workflow background',
  backgroundHint: 'Shared by every node. Changes here update the whole workflow.',
  structure: 'Edit workflow structure',
  save: 'Save workflow template',
  cancel: 'Cancel',
  closeEditor: 'Close editor',
  conflictReload:
    'This workflow was changed in another window. Reload the list before trying again.',
  conflict:
    'This workflow was changed in another window. Your draft is retained. Cancel editing and reload the list before saving again.',
  back: 'Back to workflow templates',
  draft: 'Draft',
  loading: 'Loading workflows…',
  retry: 'Retry',
  error: 'Could not load or save workflows. Please retry.',
  errorDetails: 'Error details',
  unavailableTemplate: 'Unavailable template',
  unavailableDraft: 'Unavailable editing draft',
  incompatibleTemplateDescription:
    'This template uses a format that is no longer supported. It will not be converted automatically. Delete it and create a new template.',
  invalidTemplateDescription:
    'This template contains invalid data and cannot be opened. You can delete it and create a new template.',
  incompatibleDraftDescription:
    'This editing draft uses a format that is no longer supported. It will not be converted automatically. Discarding it leaves the published template unchanged.',
  invalidDraftDescription:
    'This editing draft contains invalid data and cannot be opened. Discarding it leaves the published template unchanged.',
  unavailableDraftEditing:
    'An incompatible or invalid editing draft was kept separately. You are editing the published template. Discard the unavailable draft before saving, or save as a copy.',
  deleteDraft: 'Discard editing draft',
  deleteDraftTitle: 'Discard this editing draft?',
  deleteDraftDescription:
    'Only the saved editing draft will be removed. The published template and its workflows stay unchanged.',
  savedDraft: 'Saved as a draft',
  saveIssueHint: 'Please review the following:',
  acknowledge: 'Got it',
  close: 'Close',
  deleteTitle: 'Delete this workflow?',
  deleteBlockedTitle: 'Cannot delete this workflow template',
  deleteBlockedInUse:
    'This template is used by these workflows. Remove them before deleting the template.',
  deleteBlockedInUseFallback:
    'This template is still used by a workflow. Remove those workflows before deleting the template.',
  deleteDescription: 'The saved definition and its graph will be deleted.',
  discardTitle: 'Discard unsaved changes?',
  discardDescription: 'Your changes since opening this editor have not been saved.',
  discard: 'Discard changes',
  keep: 'Keep editing',
  graphTitle: 'Edit workflow structure',
  graphSave: 'Save graph',
  graphHint: 'Add members and drag them to arrange your team.',
  agents: 'Agents',
  permission: 'Permissions',
  blank: 'New agent',
  user: 'User',
  currentUser: 'Current user',
  userTask: 'What should the user do?',
  userTaskPlaceholder:
    'For example: review the proposal, suggest changes, and tell the development agent when to proceed.',
  issue_userTask: 'Describe what the user needs to do.',
  newNode: 'Untitled node',
  node: 'Node',
  connection: 'Connection',
  nodeName: 'Node name',
  receives: 'What this node receives',
  task: 'What this node does',
  delivers: 'What this node delivers',
  source: 'From',
  target: 'To',
  configureHint: 'Double-click to configure. When focused, press Enter to configure.',
  deleteNode: 'Delete node',
  inspectorEmpty: 'Select a member to edit its details.',
  canvasEmpty: 'Drag in or create an agent.',
  zoomIn: 'Zoom in',
  zoomOut: 'Zoom out',
  resetView: 'Fit to canvas',
  optimizeLayout: 'Optimize layout',
  issue_name: 'Add a workflow name.',
  issue_empty: 'Add at least one agent node.',
  issue_task: 'Add a node name and task.',
  issue_unknown: 'This definition needs attention.',
  moveHint: 'Use arrow keys to move the selected node; hold Shift for larger steps.'
}
type WorkflowTextKey = keyof typeof english
const chinese: Record<WorkflowTextKey, string> = {
  issue_node_model_unavailable: '节点使用的模型已不可用，请重新选择。',
  issue_node_model: '请为节点选择模型。',
  noEnabledModels: '暂无可用模型',
  modelNotSelected: '未选择模型',
  modelUnavailable: '模型不可用',
  selectModel: '选择模型',
  model: '模型',
  paletteTitle: '添加节点',
  nodeSettings: '节点配置',
  quickSettings: '智能体快捷配置',
  details: '配置',
  backgroundEmpty: '尚未填写公共背景。',
  editBackground: '编辑公共背景',
  nodeTaskTab: '任务',
  searchNodes: '搜索节点',
  addNode: '添加节点',
  closeInspector: '关闭配置面板',
  unsaved: '未保存',
  redo: '重做',
  undo: '撤销',
  structureTab: '流程设计',
  basicInfo: '基本信息',
  copy: '复制模板',
  copySuffix: '副本',
  saveCopy: '保存为副本',
  stash: '暂存修改',
  stashed: '修改已暂存，正式模板未改变。',
  restoredDraft: '已恢复暂存修改，正式模板未改变。',
  pendingEdits: '有暂存修改',
  usageTitle: '更新正在使用的模板？',
  usageDescription: '以下工作流正在使用此模板。保存后，需要重新检查并确认对话绑定，才能继续使用。',
  runningTitle: '此模板有正在运行的工作流',
  runningDescription:
    '正在运行的工作流使用了此模板，不能覆盖原模板。你可以将修改保存为独立副本，或暂存修改，稍后继续编辑。',
  runningInstance: '运行中',
  confirmPublish: '保存并要求重新确认',
  title: '工作流模板',
  create: '新建工作流模板',
  edit: '编辑工作流模板',
  delete: '删除工作流模板',
  empty: '还没有工作流模板',
  name: '名称',
  namePlaceholder: '例如：产品方案评审、版本发布验收',
  descriptionPlaceholder: '说明这个工作流适合处理什么任务、何时使用',
  backgroundPlaceholder: '填写所有节点都需要了解的目标、背景和共同要求',
  description: '简短描述',
  background: '工作流公共背景',
  backgroundHint: '所有节点共享这段背景。在这里修改会更新整个工作流。',
  structure: '编辑工作流结构',
  save: '保存工作流模板',
  cancel: '取消',
  closeEditor: '关闭编辑器',
  conflictReload: '此工作流已在其他窗口更改，请刷新列表后重试。',
  conflict: '此工作流已在其他窗口更改。当前草稿仍保留，请取消编辑并刷新列表后再保存。',
  back: '返回工作流模板列表',
  draft: '草稿',
  loading: '正在加载工作流…',
  retry: '重试',
  error: '工作流加载或保存失败，请重试。',
  errorDetails: '错误详情',
  unavailableTemplate: '模板不可用',
  unavailableDraft: '暂存修改不可用',
  incompatibleTemplateDescription:
    '此模板使用的旧格式已不再支持，不会自动转换。你可以删除此模板并重新创建。',
  invalidTemplateDescription: '此模板的数据无效，无法打开。你可以删除此模板并重新创建。',
  incompatibleDraftDescription:
    '此暂存修改使用的旧格式已不再支持，不会自动转换。删除暂存修改不会影响正式模板。',
  invalidDraftDescription: '此暂存修改的数据无效，无法打开。删除暂存修改不会影响正式模板。',
  unavailableDraftEditing:
    '另有一份旧格式或无效的暂存修改已保留。当前编辑的是正式模板，请先删除该暂存修改再保存，或保存为副本。',
  deleteDraft: '删除暂存修改',
  deleteDraftTitle: '删除这份暂存修改？',
  deleteDraftDescription: '只删除已保存的暂存修改，正式模板及其工作流保持不变。',
  savedDraft: '已保存为草稿',
  saveIssueHint: '请检查以下内容：',
  acknowledge: '知道了',
  close: '关闭',
  deleteTitle: '删除这个工作流？',
  deleteBlockedTitle: '无法删除工作流模板',
  deleteBlockedInUse: '这个模板正在被以下工作流使用。请先移除这些工作流，再删除模板。',
  deleteBlockedInUseFallback: '这个模板正在被工作流使用。请先移除使用它的工作流，再删除模板。',
  deleteDescription: '将删除已保存的工作流定义及其流程图。',
  discardTitle: '放弃未保存的修改？',
  discardDescription: '本次打开编辑器后的修改尚未保存。',
  discard: '放弃修改',
  keep: '继续编辑',
  graphTitle: '编辑工作流结构',
  graphSave: '保存工作流图',
  graphHint: '添加成员，拖动节点调整团队布局。',
  agents: '智能体',
  permission: '权限',
  blank: '新建智能体',
  user: '用户',
  currentUser: '当前用户',
  userTask: '需要用户做什么',
  userTaskPlaceholder: '例如：检查方案并提出修改意见，确认后通知开发智能体继续。',
  issue_userTask: '请填写需要用户完成的事情。',
  newNode: '未命名节点',
  node: '节点',
  connection: '连线',
  nodeName: '节点名称',
  receives: '这个节点会收到什么',
  task: '这个节点需要做什么',
  delivers: '这个节点需要交付什么',
  source: '起点',
  target: '终点',
  configureHint: '双击打开配置；选中后也可按 Enter 打开。',
  deleteNode: '删除节点',
  inspectorEmpty: '选择成员，编辑其详细配置。',
  canvasEmpty: '拖入或新建智能体。',
  zoomIn: '放大',
  zoomOut: '缩小',
  resetView: '适应画布',
  optimizeLayout: '优化布局',
  issue_name: '请填写工作流名称。',
  issue_empty: '请添加至少一个智能体节点。',
  issue_task: '请填写节点名称和任务。',
  issue_unknown: '这份定义仍有待完善。',
  moveHint: '可用方向键移动选中的节点，按住 Shift 可加大移动距离。'
}
export type WorkflowText = (key: WorkflowTextKey) => string
export function workflowText(language?: string): WorkflowText {
  const dictionary = language?.startsWith('zh') ? chinese : english
  return (key) => dictionary[key]
}
export function workflowIssueText(code: string, text: WorkflowText): string {
  const key = `issue_${code}` as WorkflowTextKey
  return key in english ? text(key) : text('issue_unknown')
}
