const english = {
  issue_node_model_unavailable: 'This node’s model is unavailable. Select an available model.',
  issue_node_model: 'Select a model for this node.',
  noEnabledModels: 'No enabled models',
  modelNotSelected: 'No model selected',
  modelUnavailable: 'Model unavailable',
  selectModel: 'Select model',
  model: 'Model',
  paletteTitle: 'Add node',
  connectNodes: 'Connect nodes',
  nodeSettings: 'Node settings',
  backgroundEmpty: 'No shared background yet.',
  editBackground: 'Edit shared background',
  nodeRulesTab: 'Flow rules',
  nodeTaskTab: 'Task',
  noMatchingTemplates: 'No matching templates',
  searchTemplates: 'Search templates',
  addNode: 'Add node',
  closeInspector: 'Close inspector',
  unsaved: 'Unsaved',
  redo: 'Redo',
  undo: 'Undo',
  structureTab: 'Structure',
  basicInfo: 'Basic information',
  title: 'Workflows',
  create: 'New workflow',
  edit: 'Edit workflow',
  delete: 'Delete workflow',
  empty: 'No workflows yet',
  name: 'Name',
  namePlaceholder: 'For example: Product proposal review, release acceptance',
  descriptionPlaceholder: 'Describe the tasks this workflow handles and when to use it',
  backgroundPlaceholder: 'Add the goals, context, and shared requirements every node should know',
  description: 'Short description',
  background: 'Workflow background',
  backgroundHint: 'Shared by every node. Changes here update the whole workflow.',
  structure: 'Edit workflow structure',
  save: 'Save workflow',
  cancel: 'Cancel',
  closeEditor: 'Close editor',
  conflictReload:
    'This workflow was changed in another window. Reload the list before trying again.',
  conflict:
    'This workflow was changed in another window. Your draft is retained. Cancel editing and reload the list before saving again.',
  back: 'Back to workflows',
  draft: 'Draft',
  valid: 'Graph validated',
  loading: 'Loading workflows…',
  retry: 'Retry',
  error: 'Could not load or save workflows. Please retry.',
  savedDraft: 'Saved as a draft',
  saveIssueHint: 'Please review the following:',
  acknowledge: 'Got it',
  close: 'Close',
  deleteTitle: 'Delete this workflow?',
  deleteDescription: 'The saved definition and its graph will be deleted.',
  discardTitle: 'Discard unsaved changes?',
  discardDescription: 'Your changes since opening this editor have not been saved.',
  discard: 'Discard changes',
  keep: 'Keep editing',
  graphTitle: 'Edit workflow structure',
  graphSave: 'Save graph',
  graphHint: 'Add nodes, then connect an output port to an input port. Drag nodes to arrange them.',
  templates: 'Subagent templates',
  blank: 'New blank node',
  newNode: 'Untitled node',
  templateEmpty: 'No saved templates. Add a blank node to begin.',
  templateHint: 'Drag onto the canvas, or click to add.',
  template: 'Subagent template',
  noTemplate: 'No template',
  missingTemplate: 'Template no longer exists',
  node: 'Node',
  connection: 'Connection',
  nodeName: 'Node name',
  receives: 'What this node receives',
  task: 'What this node does',
  delivers: 'What this node delivers',
  initialInput: 'Input from the parent agent',
  finalOutput: 'Final delivery to the parent agent',
  inputRule: 'Input rules',
  outputRule: 'Output rules',
  all: 'All flows',
  one: 'Exactly one',
  any: 'At least one',
  range: 'Quantity range',
  custom: 'Custom combination',
  min: 'Minimum',
  max: 'Maximum',
  required: 'Required',
  optional: 'Optional',
  groups: 'Selection groups',
  addGroup: 'Add group',
  removeGroup: 'Remove group',
  groupHint: 'Required flows and groups cannot overlap. Ungrouped flows are optional.',
  noFlows: 'Connect flows to configure this rule.',
  inputHint: 'These requirements decide when the node can start.',
  outputHint: 'The agent’s selected outputs must satisfy these requirements.',
  source: 'From',
  target: 'To',
  rootAgent: 'Root agent',
  rootInput: 'Root agent · Input',
  rootOutput: 'Root agent · Output',
  inputLabel: 'Entry',
  outputLabel: 'Exit',
  configureNode: 'Configure node',
  parentInput: 'Parent agent input',
  parentOutput: 'Deliver to parent agent',
  addFlow: 'Add connection',
  flowName: 'Connection label',
  entry: 'Entry',
  exit: 'Exit',
  addEntry: 'Connect entry',
  addExit: 'Connect exit',
  connecting: 'Select an input port or connect to the exit.',
  connectingEntry: 'Select a node’s input port for this entry.',
  cancelConnection: 'Cancel connection',
  inputPort: 'Input port',
  outputPort: 'Output port',
  deleteNode: 'Delete node',
  deleteFlow: 'Delete connection',
  inspectorEmpty: 'Select a node or connection to edit its details.',
  canvasEmpty: 'Drag in a template or add a blank node.',
  zoomIn: 'Zoom in',
  zoomOut: 'Zoom out',
  resetView: 'Fit to canvas',
  issue_name: 'Add a workflow name.',
  issue_empty: 'Add at least one node.',
  issue_entry: 'Connect an entry from the parent agent.',
  issue_exit: 'Connect an exit back to the parent agent.',
  issue_task: 'Add a node name and task.',
  issue_template: 'Select an available template or remove the template reference.',
  issue_unreachable: 'This node cannot be reached from an entry.',
  issue_noExit: 'This node has no path to an exit.',
  issue_inputRule: 'Input selection rules are inconsistent with the connected flows.',
  issue_outputRule: 'Output selection rules are inconsistent with the connected flows.',
  issue_unknown: 'This definition needs attention.',
  moveHint: 'Use arrow keys to move the selected node; hold Shift for larger steps.'
}
type WorkflowTextKey = keyof typeof english
const chinese: Record<WorkflowTextKey, string> = {
  issue_node_model_unavailable: '节点使用的模型已不可用，请重新选择。',
  issue_node_model: '请为节点选择模型。',
  noEnabledModels: '暂无可用模型',
  modelNotSelected: '未选择模型',
  modelUnavailable: '模型不可用',
  selectModel: '选择模型',
  model: '模型',
  paletteTitle: '添加节点',
  connectNodes: '连接节点',
  nodeSettings: '节点配置',
  backgroundEmpty: '尚未填写公共背景。',
  editBackground: '编辑公共背景',
  nodeRulesTab: '流转规则',
  nodeTaskTab: '任务',
  noMatchingTemplates: '未找到模板',
  searchTemplates: '搜索模板',
  addNode: '添加节点',
  closeInspector: '关闭配置面板',
  unsaved: '未保存',
  redo: '重做',
  undo: '撤销',
  structureTab: '流程设计',
  basicInfo: '基本信息',
  title: '工作流',
  create: '新建工作流',
  edit: '编辑工作流',
  delete: '删除工作流',
  empty: '还没有工作流',
  name: '名称',
  namePlaceholder: '例如：产品方案评审、版本发布验收',
  descriptionPlaceholder: '说明这个工作流适合处理什么任务、何时使用',
  backgroundPlaceholder: '填写所有节点都需要了解的目标、背景和共同要求',
  description: '简短描述',
  background: '工作流公共背景',
  backgroundHint: '所有节点共享这段背景。在这里修改会更新整个工作流。',
  structure: '编辑工作流结构',
  save: '保存工作流',
  cancel: '取消',
  closeEditor: '关闭编辑器',
  conflictReload: '此工作流已在其他窗口更改，请刷新列表后重试。',
  conflict: '此工作流已在其他窗口更改。当前草稿仍保留，请取消编辑并刷新列表后再保存。',
  back: '返回工作流列表',
  draft: '草稿',
  valid: '图结构已校验',
  loading: '正在加载工作流…',
  retry: '重试',
  error: '工作流加载或保存失败，请重试。',
  savedDraft: '已保存为草稿',
  saveIssueHint: '请检查以下内容：',
  acknowledge: '知道了',
  close: '关闭',
  deleteTitle: '删除这个工作流？',
  deleteDescription: '将删除已保存的工作流定义及其流程图。',
  discardTitle: '放弃未保存的修改？',
  discardDescription: '本次打开编辑器后的修改尚未保存。',
  discard: '放弃修改',
  keep: '继续编辑',
  graphTitle: '编辑工作流结构',
  graphSave: '保存工作流图',
  graphHint: '添加节点，再将出流端口连接到入流端口。拖动节点可调整布局。',
  templates: '子智能体模板',
  blank: '新建空白节点',
  newNode: '未命名节点',
  templateEmpty: '暂无已保存模板，可以先添加空白节点。',
  templateHint: '拖入画布，或点击添加。',
  template: '子智能体模板',
  noTemplate: '未使用模板',
  missingTemplate: '模板已不存在',
  node: '节点',
  connection: '连线',
  nodeName: '节点名称',
  receives: '这个节点会收到什么',
  task: '这个节点需要做什么',
  delivers: '这个节点需要交付什么',
  initialInput: '主智能体提供的输入',
  finalOutput: '最终交付给主智能体的结果',
  inputRule: '入流规则',
  outputRule: '出流规则',
  all: '全部参与',
  one: '恰好选一个',
  any: '至少选一个',
  range: '数量范围',
  custom: '自定义组合',
  min: '最少数量',
  max: '最多数量',
  required: '必选',
  optional: '可选',
  groups: '选择分组',
  addGroup: '添加分组',
  removeGroup: '删除分组',
  groupHint: '必选流与各分组不能重叠；未分组的流为可选。',
  noFlows: '请先连接流，再配置规则。',
  inputHint: '满足这些输入条件后，节点才可以启动。',
  outputHint: '智能体选择的出流必须满足这些条件。',
  source: '起点',
  target: '终点',
  rootAgent: '根智能体',
  rootInput: '根智能体 · 输入',
  rootOutput: '根智能体 · 输出',
  inputLabel: '入口',
  outputLabel: '出口',
  configureNode: '配置节点',
  parentInput: '主智能体输入',
  parentOutput: '交付主智能体',
  addFlow: '添加连线',
  flowName: '连线名称',
  entry: '输入流',
  exit: '输出流',
  addEntry: '连接输入流',
  addExit: '连接输出流',
  connecting: '选择一个入流端口，或连接到输出端。',
  connectingEntry: '请选择节点的入流端口，连接输入流。',
  cancelConnection: '取消连线',
  inputPort: '入流端口',
  outputPort: '出流端口',
  deleteNode: '删除节点',
  deleteFlow: '删除连线',
  inspectorEmpty: '选择节点或连线，编辑其详细配置。',
  canvasEmpty: '拖入一个模板，或添加空白节点。',
  zoomIn: '放大',
  zoomOut: '缩小',
  resetView: '适应画布',
  issue_name: '请填写工作流名称。',
  issue_empty: '请添加至少一个节点。',
  issue_entry: '请连接一条来自主智能体的输入流。',
  issue_exit: '请连接一条返回主智能体的输出流。',
  issue_task: '请填写节点名称和任务。',
  issue_template: '请选择可用模板，或清除模板引用。',
  issue_unreachable: '从输入流无法到达这个节点。',
  issue_noExit: '这个节点没有通往输出流的路径。',
  issue_inputRule: '入流选择规则与已连接的流不一致。',
  issue_outputRule: '出流选择规则与已连接的流不一致。',
  issue_unknown: '这份定义仍有待完善。',
  moveHint: '可用方向键移动选中的节点，按住 Shift 可加大移动距离。'
}
export type WorkflowText = (key: WorkflowTextKey) => string
export function workflowText(language?: string): WorkflowText {
  const dictionary = language?.startsWith('zh') ? chinese : english
  return (key) => dictionary[key]
}
export function workflowIssueText(code: string, text: WorkflowText): string {
  const key = `issue_${code}` as WorkflowTextKey
  return key in english ? text(key) : text('issue_unknown')
}
